### ISSUE TITLE
dpr Module import not working in the qer-app-operationssupport 

### ISSUE THREAD

**Issue by IPG-GillesRusso** [OneIdentity/IdentityManager.Imx#119]
So I was trying to debug and test some changes to the Operationssupport Portal and noticed that the import for the dpr-component and module are not working. In the app-module and app-routing module of the qer-app-operationssupport the dpr module isn't recognized. You can solve this issue by changing the import's paths from dpr to the absolute path.
For example by changing import { OutstandingModule } from 'dpr';  to -> import { OutstandingModule } from '../../../dpr/src/lib/outstanding/outstanding.module';
Additionally you need to change a funtion from private to public. This is solely a workaround as I couldn't figure out why the import isn't working. 
Any feedback would be helpful.

**Comment by hannobunjes** [comment]
Hello @IPG-GillesRusso,

The imports using module aliases (`import { OutstandingModule } from 'dpr'`) are intentional. Changing them to relative path imports may solve the issue in one context, but creates other issues because Angular cannot deal with cross-project imports.

These path aliases are defined in `imxweb/tsconfig.json`.

**Comment by IPG-GillesRusso** [comment]
Thank you for the response and clarification
