### ISSUE TITLE
Escalation Feature in the new Web Shop.

### ISSUE THREAD

**Issue by IPG-GillesRusso** [OneIdentity/IdentityManager.Imx#137]
Hi,
I recently noticed that the Escalation Tab and its functionality are either unavailabe or not implemented in the new Web Portal.
Is this a feature which will be exclusive to the old web portal or are you planning to implement this in the new Web Portal aswell?
Thank you very much.

**Comment by hannobunjes** [comment]
Hi @IPG-GillesRusso 
Are you referring to the "IT Shop escalation" page from the old web portal? If so, this is no longer a separate page. Instead, the members of the "Chief Approval Team" role see a slider that they can use to act on all open requests.

We are not using the "Escalation" term for the chief approval team anymore, because escalation steps in workflows are something different.

**Comment by IPG-GillesRusso** [comment]
Thank you for the clarification
