### ISSUE TITLE
Hide some menu items

### ISSUE THREAD

**Issue by zime-rch** [OneIdentity/IdentityManager.Imx#139]
Hi

What is the right way to hide some menu items? This even the rights to see the items are available.
Example, we would like to disable in Setup Menu the item Reports, because we do not want to provide this feature to the End User in the new web Portal.

Regards, René

**Comment by SebastianW-OneIdentity** [comment]
Hi @zime-rch

The right way to this is not to push the corresponding MenuItem with the ID "RPS_Reports" in the [projects\rps\src\lib\reports\edit-report.module.ts](https://github.com/OneIdentity/IdentityManager.Imx/blob/1d691e1f4e5a537c1244b6083baa5c2a7dc5bce0/imxweb/projects/rps/src/lib/reports/edit-report.module.ts#L98)

If you remove this code the End User cannot see this Reports Menu Item in the Setup Menu. 

However, since the page can still be accessed (if you know the route), I would also recommend that you remove the route to the reports page. Therefore you have to remove the route with the path: 'reports' in [projects\rps\src\lib\rps-config.module.ts](https://github.com/OneIdentity/IdentityManager.Imx/blob/1d691e1f4e5a537c1244b6083baa5c2a7dc5bce0/imxweb/projects/rps/src/lib/rps-config.module.ts#L40)

Regards, Sebastian

**Comment by zime-rch** [comment]
Uninstall the upgraded v8.2 ApiServer and re-install ApiServer from the Install Source v9.2 did solve this issue.
