### ISSUE TITLE
Applying the Web Portal Hotfix for the package version 9.2.1

### ISSUE THREAD

**Issue by IPG-GillesRusso** [OneIdentity/IdentityManager.Imx#144]
While applying the hotfix for the v9.2.1 I noticed besides the dll files there were also the compiled versions of a few libraries/apps. What is their purpose?

**Comment by SebastianW-OneIdentity** [comment]
@IPG-GillesRusso 
The compiled versions of the Angular libraries and apps contain all changes made to the client code for this hotfix.
Of course, if you are not using a compiled web, you will also need to wait for the changes in this hotfix to be published here on GitHub.

**Comment by IPG-GillesRusso** [comment]
I assumed the changes were already in the release from May 6th. Does that mean that you currently can't use the latest release, if you want to develop and release custom changes on the newest version, until these changes are on GitHub as well?

**Comment by SebastianW-OneIdentity** [comment]
@IPG-GillesRusso 
Oh, you're not talking about a hotfix in general but about the 9.2.1 service pack. Now I understand you!
As far as I know, the 9.2.1 SP (service pack) has not been released yet. Until this happens, we will also synchronize the repository here on GitHub to the version 9.2.1 SP. Because the changes from May 6th were not the last changes of the 9.2.1 SP

**Comment by hannobunjes** [comment]
Hi @IPG-GillesRusso ,

The answer to your question really depends on the issue. It doesn't often happen that a hotfix contains both server and client changes, but sometimes it does.
