### ISSUE TITLE
Single Sign On for qbm-app-landingpage

### ISSUE THREAD

**Issue by zime-rch** [OneIdentity/IdentityManager.Imx#150]
Has anyone managed to enforce SSO on the qbm-app-landingpage? For me and all other end users, all tiles are always displayed. However, I want to hide certain tiles, such as the administration portal, for regular users.

**Comment by hannobunjes** [comment]
Hello @zime-rch,
The landing page currently works without any prior authentication. It always shows all tiles because it does not know anything about the user. We may change this in the future and allow navigation to the various apps based on user roles, but that is not trivial because not all apps authenticate in the same way.

As a workaround, you could show qer-app-portal instead of the qbm-app-landingpage, and display links to the other apps based on user roles.

**Comment by zime-rch** [comment]
Hello @hannoquest 
Yes we have already decided to have the qer-app-portal as start page.
