### ISSUE TITLE
System Roles Properties

### ISSUE THREAD

**Issue by DominicFe** [OneIdentity/IdentityManager.Imx#155]
In the API Configuration it's possible to change the properties normally. But in the case of system roles
you can't add non-default properties. They won't show up in the main data tab of the system role. You can only add/remove the hard coded properties.

**Comment by NielsDeGroot** [comment]
This issue with "Property editors / Properties that can be edited" not working for "System roles" is also happening with "Business roles". I then tried out "Resources" but here the functionality works, strange?

**Comment by NielsDeGroot** [comment]
Hello @hannoquest 

Do you think this is a bug on the server side?
If so must I make a support call for this?

**Comment by hannobunjes** [comment]
Please open a support case if you have not already done so.

Thanks.

**Comment by NielsDeGroot** [comment]
Just got an update on this the case is now forwarded to the product team.

**Comment by NielsDeGroot** [comment]
Update on this: 
My Case # 02472297 Api server: Property editors not working for system and business roles.
Is still under investigation...

**Comment by NielsDeGroot** [comment]
Two months after submitting the support case I got the reply that they were unable to replicate the issue and asked if I could make video showing the configuration action and result. I already submitted multiple screenshots with text. This should be sufficient because it's a real simple issue. I also asked which version of the RMS.CompositionApi.Server.PlugIn.dll they used to replicate the issue, but no reply this was two weeks ago.

**Comment by NielsDeGroot** [comment]
[9.2 AngularWeb: Only the default values for (Web Portal) ServerConfig/OwnershipConfig/EditableFields/ESet are displayed in the Web. (4378120)](https://support.oneidentity.com/identity-manager/kb/4378120/9-2-angularweb-only-the-default-values-for-web-portal-serverconfig-ownershipconfig-editablefields-eset-are-displayed-in-the-web)

**Comment by BertramBo** [comment]
Hotfix #474298 solve this issue
