### ISSUE TITLE
Filter in Identities

### ISSUE THREAD

**Issue by lmd01gh** [OneIdentity/IdentityManager.Imx#174]
Hi

In the v92 angular portal, In identities, the filter screen is different depending on the user who has logged in.
For example, to the user1 the screen is:
![Captura1](https://github.com/user-attachments/assets/62a46c27-400a-4e1c-a159-7d99324072ca)

For the user2 the screen is:
![Captura](https://github.com/user-attachments/assets/049d52d2-15ea-4004-9b68-1b6168525b9f)

With PostMan I perform a GET Request to the url "BaseURL/Apiserver/portal/person/reports/datamodel" for the user1  and the result in Filter is:

"Filters": [
        {
            "Name": "isinactive",
            "Description": "Identity status",
            "Options": [
                {
                    "Value": "0",
                    "Display": "Identidades activadas"
                },
                {
                    "Value": "1",
                    "Display": "Identidades desactivadas"
                }
            ]
        },
        {
            "Name": "reports",
            "Description": "Responsibility type",
            "Options": [
                {
                    "Value": "0",
                    "Display": "Identidades con responsabilidad directa"
                },
                {
                    "Value": "1",
                    "Display": "Identidades delegadas"
                }
            ]
        }
    ]
	
The same GET request for the user2 , the result is:

"Filters": [
        {
            "Name": "reports",
            "Description": "Responsibility type",
            "Options": [
                {
                    "Value": "0",
                    "Display": "Identidades con responsabilidad directa"
                },
                {
                    "Value": "1",
                    "Display": "Identidades delegadas"
                }
            ]
        }
    ],

	
Why do the filters obtain are different? Where is that data stored? Tables? Parameters??
Any help would be greatly appreciated.

**Comment by Mathnstein** [comment]
Reading your output are you sure the user1 / user2 are correct? I would read them as flipped.

At a high level - the filters available are within the data model. Each identity will have different filters based on their roles. The values set can come from three places:
1. The table has hard coded filters applied: we may have a place or two that directly searches for a filter and applies a value by default (i.e compliance policies). There is no way to supersede this as its in the code.
2. The table has a default view configuration: This is managed within the admin portal, one can set default filters for everyone.
3. The table has a user-saved default view configuration: The identity has elected to use their own view config, this is only for that particular identity. This is managed in the saved config UI on that page (gear icon -> saved configs -> Star icon for default choice)

**Comment by lmd01gh** [comment]
Hi,
Indeed, I had inverted the images. I have already corrected it. 
You mentioned that there are three tables that store this information/configuration  depending on where the filters are set. 
But, could you tell me the names of the tables or how the configuration is done in the administration portal? Thank you for your help.

**Comment by Mathnstein** [comment]
The information is scattered around various tables - but as mentioned there is a per-user UI that can save configs (One can apply whatever filters they want, including sort and search and save this) then choose that to be a default. Upon loading the page, this state will be re-applied. See the viewconfig api call for this.
![image](https://github.com/user-attachments/assets/0a19e399-c509-4330-94a2-c2fafc70d8c2)

As for the admin portal and setting defaults for **everyone**, you can search for "view config" in the web portal section of the admin configuration to see the various options that can be set.
![image](https://github.com/user-attachments/assets/c846a374-3f81-4f38-ad37-9ed4104fc31d)

But also as I mentioned, some situations call for hard-coded filter setting due to specific logic that may be role or state dependent - so there are some tables that can have a filter applied from the code and not from a default config.

I've requested this be thoroughly documented though as I can see how its not clear.

If this is not enough then I suggest opening a support case on the matter.

**Comment by hannobunjes** [comment]
Hi,
The filters are hard-coded to be based on a role. However, inactive/active identities can also by filtered using the "custom filter" tab.
