### ISSUE TITLE
missing await in new-request-product.component.ts 

### ISSUE THREAD

**Issue by gitpm** [OneIdentity/IdentityManager.Imx#180]
new-request-product.component.ts -> [Link](https://github.com/OneIdentity/IdentityManager.Imx/blob/b489b3b7e9ce35a6bb11919025d9c4c84e9243fc/imxweb/projects/qer/src/lib/new-request/new-request-product/new-request-product.component.ts) -> Line 344 ff.

        if (firstIteration && (this.selectedServiceCategoryUID || this.selectedServiceItemUID)) {
          **this.setupSelection();**
          firstIteration = false;
        } else {
          this.dynamicDataSource.setup(true);
          **this.getProductData(true);**
        }

For  the async-methods  **this.setupSelection();** and the  **this.getProductData(true);**  the "**await**" is missing

**Comment by asattler** [comment]
Hi Peter, 
I could imagine that this is done by intention, as UI should not be blocked while waiting. 
If you check the rest of the file, you see that the await is missing in multiple parts - so I don't think it's an accident.

But, if this is the case I would recommend a comment in the code so that, in the future, other developers able to understand why this is done ;-)

**Comment by hannobunjes** [comment]
Hi,
Thanks for pointing this out.
It does not make a difference right now, because nothing happens after each of the asynchronous function calls. However, once you start adding code to this method, the missing `await`s can come back to bite you, so they should be there -- we will fix this.
By the way, the UI will not be blocked either way.
