### ISSUE TITLE
Please, recheck fix for 465213

### ISSUE THREAD

**Issue by juancarloscamargo** [OneIdentity/IdentityManager.Imx#199]
Following an issue that I created yesterday and could solve on my own, I would recommend rechecking this bug:

- 465213: Fixes an infinite loop, if the an invalid value is set on a basic CDR.

from the latest commit. Namely, editor-base.ts after the patch does not work if there's a server error (a template generates an exception, for example). First time it fails it wont allow further corrections and the column value won't update.  Seems like the error is never cleared. So the only workaround here is close the form and restart it. 
In this screenshot:
![image](https://github.com/user-attachments/assets/01ae8046-27e4-4b34-975e-4ed7b981f94b)

, the value is invalid. Later corrections are not updating the value, however, even the value this time is correct:

![image](https://github.com/user-attachments/assets/5570e936-efbc-4d16-bfc1-463efbd324d9)

Before the patch it worked somehow. If you apply corrections to the column, the value is updated but the control keeps the invalid mark and the form is never clean to save. If the following screenshot, the value is valid , but the field remains unclean:

![image](https://github.com/user-attachments/assets/56de15f7-340c-4def-9b53-8e61cb46ffd4)

Regards!

**Comment by flofiedler** [comment]
I tracked down the issue to a change of the writeValue method in **cdr > editor.base** which was already buggy before (459770).

https://github.com/OneIdentity/IdentityManager.Imx/blob/0ebeb21839d1dbb137f0e02219901039733aba18/imxweb/projects/qbm/src/lib/cdr/editor-base.ts#L197

**Steps to solve the problem:**

1. Go to _imxweb/projects/qbm/src/lib/cdr/editor-base.ts_
2. Add a condition in l.197 so that it really only checks for client errors as stated in the debug log: 
Replace `if (this.control.errors)` with `if (this.control.errors && !this.lastError)`
3. Update the validity of the field when there is no server error by resetting the error state of the control after l.212:
`this.lastError = undefined;` becomes `this.lastError = undefined; this.control.setErrors(null, { emitEvent: true });`

That's it!

Complete method:

```javascript
private async writeValue(value: any): Promise<void> {
    if (this.control.errors && !this.lastError) {
      this.logger.debug(this, 'writeValue - client validation failed');
      return;
    }
    this.logger.debug(this, 'writeValue called with value', value);

    if (!this.columnContainer.canEdit || this.columnContainer.value === value) {
      return;
    }

    this.isBusy = true;
    this.isWriting = true;
    try {
      this.logger.debug(this, 'writeValue - PutValue...');
      await this.columnContainer.updateValue(value);
      this.lastError = undefined;
      this.control.setErrors(null, { emitEvent: true });
    } catch (e) {
      this.lastError = e;
      this.logger.error(this, e);
      this.control.updateValueAndValidity({ emitEvent: true });
    } finally {
      this.isBusy = false;
      this.isWriting = false;
      if (!this.control.hasError('generalError') && this.control.value !== this.columnContainer.value) {
        this.control.setValue(this.columnContainer.value, { emitEvent: false });
        this.logger.debug(this, 'form control value is set to', this.control.value);
      }
    }

    this.valueHasChanged.emit({ value, forceEmit: true });
  }
```

Regards, Florian

**Comment by juancarloscamargo** [comment]
Thanks @flofiedler ! Yes, that was it. 
Regards!

**Comment by asattler** [comment]
Even though Juan closed this issue, the possible fix from Florian means that there is something to do for One Identity. @hannoquest @Mathnstein  can you please confirm, that you're aware of this issue?

**Comment by hannobunjes** [comment]
@asattler Yes we are looking at this. Thanks to @juancarloscamargo for raising this and @flofiedler for the solution.

**Comment by juancarloscamargo** [comment]
Hi @hannoquest , never mind! Would you like me to reopen it?
