### ISSUE TITLE
ApiServer imxclient (local development)

### ISSUE THREAD

**Issue by zime-rch** [OneIdentity/IdentityManager.Imx#50]
During the development I have found that I miss all configurations from API Server -> e.g. imx and Portal.

Whenever I start the imxclient I can access with http://localhost:8182 and the API Konfiguration is also available, but no configuration is loaded. I can configure some values, and take it over locally or globally, and they work as long imxclient is started. Somehow they are not persistent and the next time when I start imxclient the configuration is gone.

The easiest way would be if I could copy a  CCC.CompositionApi.global.json from the web server to a local directory , so that I can develop with the setting we have configured in our environment.

**Comment by hannoquest** [comment]
Hi,

The configuration is currently not copied automatically for locally run servers. The reason is that the `CCC.CompositionApi.global.json` file is only assigned to the "API Server" (IIS) machine role, not the "Development" machine role.

You can manually copy the file as a workaround.

Either way, the API Server configuration file is not managed by the HTML5 workspace, so this would be better managed as a regular RFE for Identity Manager.

**Comment by zime-rch** [comment]
It works so far with the configuration of the Api Projects, only the logo is a bit tricky. We have the logo configured as followed: 
http://localhost:8182/logoimage/logoxy.png, that means that the logo is in the folder:  ..\inetpub\logoimage\logoxy.png.
Where do I need to copy the logo on local development environment? I tried the binary directory, the webimx folder in binary directory or also the angular workspace directory, none of these has worked.

**Comment by hannoquest** [comment]
The locally hosted API Server does not resolve any file paths. That functionality is actually provided by the IIS, not the API Server.

**Comment by zime-rch** [comment]
Okay, thank you
